env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'plugin:react/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'cypress'
  - 'react'
rules: {}
ignorePatterns:
  - 'cypress/plugins/index.js'
