stages:
  - lint
  - build
  - deploy

include:
  - project: 'cocainefarm/templates/ci'
    file: '/container.base.yaml'

default:
  tags:
    - k8s

.cache_backend: &cache_backend
  cache:
    key:
      files:
        - backend/package.json
    paths:
      - node_modules/
      - /usr/local/share/.cache/yarn/v6

.cache_frontend: &cache_frontend
  cache:
    key:
      files:
        - frontend/package.json
    paths:
      - node_modules/
      - /usr/local/share/.cache/yarn/v6

##################################################
# LINT

variables:
  BASE_IMAGE: node:15.1.0-alpine

.lint:
  image: $BASE_IMAGE
  stage: lint
  script:
    - yarn install
    - yarn lint
  only:
    refs:
      - lmrdashboard
      - tags
      - merge_requests

lint:backend:
  extends: .lint
  <<: *cache_backend
  before_script:
    - cd backend

lint:frontend:
  extends: .lint
  <<: *cache_frontend
  before_script:
    - cd frontend


##################################################
# BUILD

build:backend:lmrdashboard:
  extends: .container:base
  stage: build
  <<: *cache_backend
  variables:
    DESTINATION: "kube.cat/${CI_KUBECAT_NAMESPACE}/${CI_PROJECT_NAME}-backend:${CI_COMMIT_SHORT_SHA}"
    BUILD_PATH: "backend/"
  only:
    refs:
      - lmrdashboard

build:backend:tags:
  extends: .container:base
  stage: build
  <<: *cache_backend
  variables:
    DESTINATION: "kube.cat/${CI_KUBECAT_NAMESPACE}/${CI_PROJECT_NAME}-backend:${CI_COMMIT_TAG} kube.cat/${CI_KUBECAT_NAMESPACE}/${CI_PROJECT_NAME}-backend:latest"
    BUILD_PATH: "backend/"
  only:
    refs:
      - tags


build:frontend:lmrdashboard:
  extends: .container:base
  stage: build
  <<: *cache_frontend
  variables:
    DESTINATION: "kube.cat/${CI_KUBECAT_NAMESPACE}/${CI_PROJECT_NAME}-frontend:${CI_COMMIT_SHORT_SHA}"
    BUILD_PATH: "frontend/"
    BUILD_ARGS: "LMRD_EVENT_SOURCE=https://lmrdev.cocaine.farm/api/test"
  only:
    refs:
      - lmrdashboard

build:frontend:tags:
  extends: .container:base
  stage: build
  <<: *cache_frontend
  variables:
    DESTINATION: "kube.cat/${CI_KUBECAT_NAMESPACE}/${CI_PROJECT_NAME}-frontend:${CI_COMMIT_TAG} kube.cat/${CI_KUBECAT_NAMESPACE}/${CI_PROJECT_NAME}-frontend:latest"
    BUILD_PATH: "frontend/"
    BUILD_ARGS: "LMRD_EVENT_SOURCE=https://lmr.cocaine.farm/api/test"
  only:
    refs:
      - tags

##################################################
# DEPLOY

deploy:prod:
  image: kube.cat/cocainefarm/helmfile:v0.135.0
  stage: deploy
  environment:
    name: production
    url: https://lmr.cocaine.farm
  before_script:
    - gpg --import "$COCAINEFARM_GPG_PRIVKEY"
  script:
    - helmfile apply
  only:
    refs:
      - tags

deploy:dev:
  image: kube.cat/cocainefarm/helmfile:v0.135.0
  stage: deploy
  environment:
    name: dev
    url: https://lmrdev.cocaine.farm
  before_script:
    - gpg --import "$COCAINEFARM_GPG_PRIVKEY"
  script:
    - helmfile apply
  only:
    refs:
      - lmrdashboard
