version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lmrd
    volumes:
      - ./backend/irc/utils/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backend/irc/utils/db/data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
