repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

environments:
  production:
    values:
      - tagOverride: {{ env "CI_COMMIT_TAG" | quote }}
      - host: {{ requiredEnv "CI_ENVIRONMENT_URL" | trimPrefix "https://" | quote }}
      - irc:
          username: lmrdashboard
          channel: "#linuxmasterrace"
  staging:
    values:
      - tagOverride: {{ requiredEnv "CI_COMMIT_SHORT_SHA" | quote }}
      - host: {{ requiredEnv "CI_ENVIRONMENT_URL" | trimPrefix "https://" | quote }}
      - irc:
          username: lmrstageboard
          channel: "#aboftytest"

helmDefaults:
  createNamespace: false

releases:
  - name: lmrdashboard
    chart: ./chart
    namespace: {{ requiredEnv "KUBE_NAMESPACE" }}
    secrets:
      - ./secrets/mariadb.yaml
      - ./secrets/irc_user.yaml
    values:
      - image:
          tagOverride: {{ .Values.tagOverride }}
      - irc:
          channel: {{ .Values.irc.channel | quote }}
          username: {{ .Values.irc.username | quote }}
      - gitlab:
          envSlug: {{ requiredEnv "CI_ENVIRONMENT_SLUG" | quote }}
          projectSlug: {{ requiredEnv "CI_PROJECT_PATH_SLUG" | quote }}
      - ingress:
          enabled: true
          hosts:
            - host: {{ .Values.host }}
              paths:
                - /
          tls:
            - secretName: cocaine-farm-tls
              hosts:
                - {{ .Values.host }}
      - mariadb:
          architecture: standalone
          auth:
            database: lmrd
          primary:
            persistence:
              enabled: true
              storageClass: "ssd"
              accessModes:
                - ReadWriteOnce
              size: 8Gi
