apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lmrdashboard.fullname" . }}-irc-user
  labels:
    {{- include "lmrdashboard.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.irc.username | quote }}
  password: {{ .Values.irc.password | quote }}
