apiVersion: v1
kind: Service
metadata:
  name: {{ include "lmrdashboard.fullname" . }}-backend
  labels:
    {{- include "lmrdashboard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  {{- with .Values.backend.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.backend.service.externalIPs }}
  externalIPs:
{{ . | toYaml | nindent 4 }}
  {{- end }}
  clusterIP: None
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: backend
      protocol: TCP
      name: backend
  selector:
    {{- include "lmrdashboard.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lmrdashboard.fullname" . }}-frontend
  labels:
    {{- include "lmrdashboard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  {{- with .Values.frontend.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.frontend.service.externalIPs }}
  externalIPs:
{{ . | toYaml | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: frontend
      protocol: TCP
      name: frontend
  selector:
    {{- include "lmrdashboard.selectorLabels" . | nindent 4 }}
